#!/usr/bin/env node
// spec-backlog.mjs — turn dangling § citations into a writing work-list.
//
// engine.js cites SPEC sections that do not exist. The rules those citations
// point at are real and already documented — in the engine's own comments,
// which are where this codebase does its reasoning. This script pairs each
// missing section with the comment block that cites it, so writing the
// constitution is an editing job over existing prose rather than an
// archaeology job over 14,000 lines.
//
// NON-CONSENSUS: static extraction. Emits markdown to stdout.
//
// Usage: node spec-backlog.mjs > SPEC-BACKLOG.md

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const engine = fs.readFileSync(path.resolve(here, 'engine.js'), 'utf8').split('\n')
const spec = fs.readFileSync(path.resolve(here, 'SPEC.md'), 'utf8')

const headings = new Set()
for (const m of spec.matchAll(/^#{1,4}\s+(\d+[a-z]{0,3}(?:-[iv]+)?)[.\s]/gm)) headings.add(m[1])

// Collect citations with their line numbers.
const hits = new Map() // section -> [lineIdx]
engine.forEach((line, i) => {
  for (const m of line.matchAll(/§\s?(\d+[a-z]{0,3}(?:-[iv]+)?)\b/g)) {
    const sec = m[1]
    if (Number(sec) >= 1000) continue // line number, not a section
    if (headings.has(sec)) continue
    if (!hits.has(sec)) hits.set(sec, [])
    hits.get(sec).push(i)
  }
})

// Pull the contiguous comment block containing a line.
const isComment = (l) => /^\s*(\/\/|\/\*|\*)/.test(l)
function commentBlock(i) {
  let a = i, b = i
  if (!isComment(engine[i])) {
    // citation sits in code; walk up to the comment above it
    let j = i - 1
    while (j >= 0 && !isComment(engine[j]) && engine[j].trim() !== '') j--
    if (j < 0 || !isComment(engine[j])) return null
    a = b = j
  }
  while (a > 0 && isComment(engine[a - 1])) a--
  while (b < engine.length - 1 && isComment(engine[b + 1])) b++
  return { start: a, end: b, text: engine.slice(a, b + 1).join('\n') }
}

const sortKey = (s) => {
  const n = parseInt(s, 10)
  return [n, s.replace(/^\d+/, '')]
}
const sections = [...hits.keys()].sort((x, y) => {
  const [a1, a2] = sortKey(x), [b1, b2] = sortKey(y)
  return a1 - b1 || (a2 < b2 ? -1 : a2 > b2 ? 1 : 0)
})

console.log(`# SPEC backlog — sections cited by the engine but never written\n`)
console.log(`${sections.length} missing sections, ${[...hits.values()].reduce((a, b) => a + b.length, 0)} citation sites.`)
console.log(`Generated by \`node spec-backlog.mjs\`. Each entry carries the engine`)
console.log(`comment that cites it: the rule is already argued there, it has simply`)
console.log(`never been promoted into the constitution.\n`)
console.log(`Writing one of these means: read the block, write the section into`)
console.log(`SPEC.md under that exact number, re-run \`node spec-conformance.mjs\`.\n`)
console.log(`---\n`)

for (const sec of sections) {
  const lineIdxs = hits.get(sec)
  console.log(`## §${sec}`)
  console.log(`\n${lineIdxs.length} citation site${lineIdxs.length > 1 ? 's' : ''}: ${lineIdxs.map(i => `engine.js:${i + 1}`).join(', ')}\n`)
  const seen = new Set()
  let shown = 0
  for (const i of lineIdxs) {
    const blk = commentBlock(i)
    if (!blk || seen.has(blk.start)) continue
    seen.add(blk.start)
    if (shown++ >= 2) break // two blocks is plenty of context
    const body = blk.text.replace(/^\s*(\/\/ ?|\/\*+ ?|\* ?)/gm, '').trimEnd()
    console.log('```')
    console.log(`engine.js:${blk.start + 1}-${blk.end + 1}`)
    console.log(body)
    console.log('```\n')
  }
  if (!shown) console.log(`_(cited from code with no adjacent comment — read engine.js:${lineIdxs[0] + 1} directly)_\n`)
}
