#!/usr/bin/env node
// spec-index.mjs: A WAY INTO A DOCUMENT THAT IS NOT WRITTEN TO BE READ STRAIGHT
// THROUGH.
//
// §0-i says what this constitution is: "written as a record, not as a manual",
// a document that accretes, where a section saying a thing was tried and
// repealed is as binding as one stating a rule. That is a deliberate choice and
// it should stand. What it costs is that the sections run in the order they
// were written, so §6l sits between §2f and §2h, and a reader looking for what
// a stall costs has nowhere to start but the top.
//
// An index fixes that without moving a line of law. It is navigation, so it is
// generated rather than written: a hand-kept contents page for four hundred and
// fifty sections is a list that goes wrong the first week and then stays wrong.
//
//   node spec-index.mjs            write SPEC-INDEX.md for review
//   node spec-index.mjs --write    splice into SPEC.md between the markers
import { readFileSync, writeFileSync } from 'fs'

const WRITE = process.argv.includes('--write')
const raw = readFileSync(new URL('./SPEC.md', import.meta.url), 'utf8')
const B = '<!-- BEGIN GENERATED: index -->', E = '<!-- END GENERATED: index -->'

// The index describes the BODY. Appendix D is a backlog of drafts, marked
// unratified on every one of them, and listing it here would present a hundred
// and forty-five unadopted paragraphs as if they were chapters.
const APPENDIX = raw.indexOf('\n# Appendix D.')
const body = raw.slice(0, APPENDIX === -1 ? raw.length : APPENDIX)

// Sections in the order the file has them, which is the order a citation
// resolves in. The grouping is by the number, so §6a..§6dj read together even
// though they are scattered over nine thousand lines.
const rows = []
for (const m of body.matchAll(/^(#{2,3})\s+([0-9]+[a-z.-]*?)\.\s+(.+)$/gm)) {
  rows.push({ id: m[2], title: m[3].trim().replace(/\s+/g, ' ') })
}

const key = (id) => {
  const m = id.match(/^(\d+)([a-z]*)(?:-(\w+))?$/)
  if (!m) return [9999, 'zzz', 99]
  const roman = { ii: 2, iii: 3, iv: 4, v: 5, vi: 6, vii: 7 }
  return [Number(m[1]), (m[2] || '').padEnd(4, ' '), roman[m[3]] ?? 1]
}
rows.sort((a, b) => {
  const x = key(a.id), y = key(b.id)
  return x[0] - y[0] || x[1].localeCompare(y[1]) || x[2] - y[2]
})

const out = [
  '<!-- ' + rows.length + ' sections, listed by number. GENERATED by spec-index.mjs;',
  '     do not edit by hand, run `node spec-index.mjs --write`. -->',
  '',
]
let part = null
for (const r of rows) {
  const top = r.id.match(/^\d+/)[0]
  if (top !== part) { out.push(''); part = top }
  out.push(`- **§${r.id}** ${r.title}`)
}
out.push('')
const text = out.join('\n')

if (!WRITE) {
  writeFileSync(new URL('./SPEC-INDEX.md', import.meta.url), text)
  console.log('wrote SPEC-INDEX.md: ' + rows.length + ' sections')
} else {
  if (!raw.includes(B)) {
    console.log('no marker pair in SPEC.md. Add where the index belongs, then re-run:')
    console.log('  ' + B + '\n  ' + E)
    process.exit(1)
  }
  const before = raw.slice(0, raw.indexOf(B) + B.length)
  const after = raw.slice(raw.indexOf(E))
  writeFileSync(new URL('./SPEC.md', import.meta.url), before + '\n' + text + '\n' + after)
  console.log('spliced an index of ' + rows.length + ' sections into SPEC.md')
}
